### ISSUE TITLE
Only 'res' key contains data

### ISSUE THREAD

**Issue by pkpowell** [frpz/ping#1]
`Ping.host('localhost')` always returns false values (lost, online, status), even if the host exists.
The res key contains the correct ping data.
What am I doing wrong?

```
{ ip: 'localhost',
  latency: 0,
  lost: 100,
  online: false,
  res: 'PING localhost (127.0.0.1): 56 data bytes\n64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.043 ms\n\n--- localhost ping statistics ---\n1 packets transmitted, 1 packets received, 0.0% packet loss\nround-trip min/avg/max/stddev = 0.043/0.043/0.043/0.000 ms\n',
  status: 'offline' }
```

**Comment by frpz** [comment]
Hello,

You are doing nothing wrong, but in the result you have, the line with the statistics doesn't start with "rtt" (as on my ubuntu), but with "round-trip". Which system are you using?

I modified the code, so now it should work. Try updating to 1.0.3 and tell me if it's better.

**Comment by pkpowell** [comment]
This was on OS X (10.8 and 10.11).
Awesome, much better.
One more thing. Is it be possible to _not_ round the latency? Currently anything under 1 ms is returned as `0`.

**Comment by frpz** [comment]
I've change the rounding to be at the first decimal.
