### ISSUE TITLE
Remove lodash 3.10.1_1 dependencey

### ISSUE THREAD

**Issue by ExcelNet-Public** [frpz/ping#3]
This package is forcing an unnecessary dependency on a specific version of the erasaur:meteor-lodash package that is not allowing it to be updated to the current 4.0.0.  Please fix

**Comment by frpz** [comment]
Yes you are right, this dep is useless, I removed it.

Sorry for the delay.

**Comment by ExcelNet-Public** [comment]
Thanks, resolved the issue!
